import path from "node:path";
import { BrokerError } from "./errors.js";
import { runCommand } from "./process.js";
import type { BatchRecord, BrokerConfig, TaskRecord } from "./types.js";
import type { GitRepository } from "./git.js";

export interface PublicationResult {
  mode: "branch" | "pull-request";
  branchName: string;
  pullRequestUrl?: string;
  /** True when an earlier attempt had already opened this batch's pull request. */
  reusedPullRequest?: boolean;
}

function renderTitle(template: string, batch: BatchRecord): string {
  return template.replaceAll("{batchId}", batch.id).replaceAll("{taskCount}", String(batch.taskIds.length));
}

function pullRequestBody(batch: BatchRecord, tasks: TaskRecord[]): string {
  const rows = tasks.map((task) => `- \`${task.id}\`${task.title ? ` — ${task.title}` : ""}`);
  return [
    "## Merge Broker batch",
    "",
    `Batch: \`${batch.id}\``,
    `Base: \`${batch.baseBranch}\` at \`${batch.baseSha}\``,
    "",
    "### Tasks",
    "",
    ...rows,
    "",
    "### Validation",
    "",
    ...batch.validations.map((result) => `- ${result.exitCode === 0 ? "✅" : "❌"} ${result.name}`),
    ...(batch.candidate
      ? [
          "",
          "### Merge authorization",
          "",
          `- Candidate revision: \`${batch.candidate.revision}\``,
          `- Candidate SHA: \`${batch.candidate.sha}\``,
          `- Candidate base: \`${batch.candidate.baseSha}\``,
          `- Policy: \`${batch.candidate.policyRevision}\``,
          `- State at publication: \`${batch.candidate.state}\``,
          "- Candidate nomination does **not** authorize merging.",
        ]
      : []),
    ...(batch.provenancePath
      ? ["", "### Provenance", "", `- Batch manifest: \`${batch.provenancePath}\``]
      : []),
    "",
    "Generated by Agent Merge Broker. Commit receipts and validation output remain in local broker state.",
  ].join("\n");
}

export async function publishBatch(options: {
  repo: GitRepository;
  config: BrokerConfig;
  batch: BatchRecord;
  tasks: TaskRecord[];
}): Promise<PublicationResult> {
  const { repo, config, batch, tasks } = options;
  if (!batch.branchName) throw new BrokerError("NO_BRANCH", `Batch ${batch.id} has no integration branch.`);
  if (config.publish.mode === "none") {
    throw new BrokerError("PUBLISH_DISABLED", "Publishing is disabled in .merge-broker/config.json.");
  }
  await repo.push(config.remote, batch.branchName);
  if (config.publish.mode === "branch") {
    return { mode: "branch", branchName: batch.branchName };
  }

  // Publication is retried after any partial failure, so it must not open a second pull request for
  // a branch that already has one. A lookup that *fails* is not an answer: creating one anyway is
  // how a retry during a forge outage ends up with duplicates, so refuse instead and let the
  // operator retry when the forge can answer.
  const existing = await findOpenPullRequest(repo.root, config, batch.branchName);
  if (existing) {
    return {
      mode: "pull-request",
      branchName: batch.branchName,
      pullRequestUrl: existing,
      reusedPullRequest: true,
    };
  }

  const title = renderTitle(config.publish.titleTemplate, batch);
  const args = [
    "pr",
    "create",
    "--base",
    config.baseBranch,
    "--head",
    batch.branchName,
    "--title",
    title,
    "--body-file",
    "-",
  ];
  if (config.publish.draft) args.push("--draft");
  for (const label of config.publish.labels) args.push("--label", label);
  const result = await runCommand("gh", args, {
    cwd: repo.root,
    input: pullRequestBody(batch, tasks),
  });
  const url = result.stdout
    .split("\n")
    .map((line) => line.trim())
    .find((line) => /^https?:\/\//u.test(line));
  if (!url) {
    throw new BrokerError("PUBLISH_FAILED", "GitHub CLI did not return a pull request URL.", {
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
  // Auto-merge is deliberately *not* attempted here. It used to be, and a failed attempt threw away
  // the pull request this function had just created: the caller recorded nothing, `batch sync` could
  // not see a batch still marked `prepared`, and retrying risked a duplicate. Enabling it is the
  // caller's separate, recoverable step.
  return { mode: "pull-request", branchName: batch.branchName, pullRequestUrl: url, reusedPullRequest: false };
}

/**
 * Closes a superseded pull request. Best effort by design: the batch it belonged to has already been
 * replaced locally, and a forge that cannot be reached must not block that. The caller reports what
 * was left open.
 */
export async function closePullRequest(
  repoRoot: string,
  pullRequestUrl: string,
  comment: string,
): Promise<boolean> {
  const result = await runCommand(
    "gh",
    ["pr", "close", pullRequestUrl, "--comment", comment],
    { cwd: repoRoot, allowFailure: true },
  );
  return result.exitCode === 0;
}

/** Refreshes the informational PR body after the broker replaces a candidate on the same branch. */
export async function updatePullRequestBody(
  repoRoot: string,
  pullRequestUrl: string,
  batch: BatchRecord,
  tasks: TaskRecord[],
): Promise<void> {
  const result = await runCommand(
    "gh",
    ["pr", "edit", pullRequestUrl, "--body-file", "-"],
    { cwd: repoRoot, input: pullRequestBody(batch, tasks), allowFailure: true },
  );
  if (result.exitCode !== 0) {
    throw new BrokerError("PULL_REQUEST_UPDATE_FAILED", "The candidate was updated but its PR description was not.", {
      pullRequestUrl,
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
}

/**
 * The open pull request for this branch, or null when there is provably none.
 *
 * Throws when the forge cannot answer. "I do not know" must not read as "there is none", because
 * the caller's response to null is to create one.
 */
async function findOpenPullRequest(
  repoRoot: string,
  config: BrokerConfig,
  branchName: string,
): Promise<string | null> {
  const result = await runCommand(
    "gh",
    [
      "pr", "list",
      "--head", branchName,
      "--base", config.baseBranch,
      "--state", "open",
      "--json", "url",
      "--limit", "1",
    ],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode !== 0) {
    throw new BrokerError(
      "PULL_REQUEST_LOOKUP_FAILED",
      `Could not determine whether ${branchName} already has an open pull request, so publication stopped rather than risk opening a second one. The branch is pushed; retry when the forge responds.`,
      { branchName, stdout: result.stdout, stderr: result.stderr },
    );
  }
  try {
    const rows = JSON.parse(result.stdout) as Array<{ url?: string }>;
    return rows[0]?.url ?? null;
  } catch {
    throw new BrokerError(
      "PULL_REQUEST_LOOKUP_FAILED",
      `Could not read the pull request list for ${branchName}.`,
      { branchName, stdout: result.stdout },
    );
  }
}

export interface PullRequestMergeState {
  state: string;
  mergeStateStatus: string;
  mergeable: string;
}

/**
 * GitHub's own view of whether a pull request can merge. Returns undefined when the state cannot be
 * read at all, which is treated as "do not merge" rather than as permission to proceed.
 */
export async function readMergeState(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<PullRequestMergeState | undefined> {
  const result = await runCommand(
    "gh",
    ["pr", "view", pullRequestUrl, "--json", "state,mergeStateStatus,mergeable"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode !== 0) return undefined;
  try {
    const value = JSON.parse(result.stdout) as Partial<PullRequestMergeState>;
    return {
      state: value.state ?? "UNKNOWN",
      mergeStateStatus: value.mergeStateStatus ?? "UNKNOWN",
      mergeable: value.mergeable ?? "UNKNOWN",
    };
  } catch {
    return undefined;
  }
}

/**
 * Hands the merge decision to GitHub: it lands the pull request once required checks pass. The
 * broker never pushes to the base branch, so branch protection stays authoritative. A batch that
 * falls behind is re-cut and re-signed; post-assembly update merges are intentionally unverifiable.
 */
export async function enableAutoMerge(
  repoRoot: string,
  pullRequestUrl: string,
  config: BrokerConfig,
  expectedHeadSha?: string,
): Promise<boolean> {
  const headGuard = expectedHeadSha ? ["--match-head-commit", expectedHeadSha] : [];
  const result = await runCommand(
    "gh",
    ["pr", "merge", pullRequestUrl, "--auto", ...headGuard, `--${config.publish.mergeMethod}`],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode === 0) return true;

  // GitHub refuses to queue auto-merge on a pull request that is already mergeable, which happens
  // whenever the required checks finish before publication returns. Ask GitHub what the state is
  // instead of reading the CLI's prose, which differs across gh versions and locales.
  const mergeState = await readMergeState(repoRoot, pullRequestUrl);
  if (mergeState?.state === "MERGED") return true;
  if (mergeState?.mergeStateStatus === "CLEAN") {
    // "CLEAN" means mergeable with every required check already passed, so merging now is exactly
    // what the auto-merge queue would have done.
    const direct = await runCommand("gh", [
      "pr", "merge", pullRequestUrl, ...headGuard, `--${config.publish.mergeMethod}`,
    ], {
      cwd: repoRoot,
      allowFailure: true,
    });
    if (direct.exitCode === 0) return true;
    throw new BrokerError("AUTO_MERGE_FAILED", "The pull request reported a clean merge state but did not merge.", {
      pullRequestUrl,
      mergeState,
      stdout: direct.stdout,
      stderr: direct.stderr,
    });
  }
  throw new BrokerError(
    "AUTO_MERGE_FAILED",
    "Could not enable auto-merge on the published pull request. Enable auto-merge in the repository settings, or set publish.autoMerge to false.",
    {
      pullRequestUrl,
      ...(mergeState ? { mergeState } : {}),
      stdout: result.stdout,
      stderr: result.stderr,
    },
  );
}

/** Stops a queued merge before approval is revoked or a candidate is revised. */
export async function disableAutoMerge(repoRoot: string, pullRequestUrl: string): Promise<boolean> {
  const result = await runCommand(
    "gh",
    ["pr", "merge", pullRequestUrl, "--disable-auto"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode === 0) return true;
  const state = await readMergeState(repoRoot, pullRequestUrl);
  if (state?.state === "MERGED") return false;
  throw new BrokerError("AUTO_MERGE_DISABLE_FAILED", "Could not disable auto-merge before revoking approval.", {
    pullRequestUrl,
    stdout: result.stdout,
    stderr: result.stderr,
  });
}

export interface PullRequestCheck {
  name: string;
  status: string;
  conclusion?: string;
  detailsUrl?: string;
}

export interface PullRequestState {
  state: string;
  mergedAt?: string;
  mergeCommitSha?: string;
  headRefOid?: string;
  baseRefOid?: string;
  baseRefName?: string;
  mergeStateStatus?: string;
  mergeable?: string;
  reviewDecision?: string;
  checks: PullRequestCheck[];
}

export async function inspectPullRequest(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<PullRequestState> {
  const result = await runCommand(
    "gh",
    [
      "pr", "view", pullRequestUrl, "--json",
      "state,mergedAt,mergeCommit,headRefOid,baseRefOid,baseRefName,mergeStateStatus,mergeable,reviewDecision,statusCheckRollup",
    ],
    { cwd: repoRoot },
  );
  const value = JSON.parse(result.stdout) as {
    state: string;
    mergedAt?: string | null;
    mergeCommit?: { oid?: string } | null;
    headRefOid?: string;
    baseRefOid?: string;
    baseRefName?: string;
    mergeStateStatus?: string;
    mergeable?: string;
    reviewDecision?: string;
    statusCheckRollup?: Array<{
      __typename?: string;
      name?: string;
      context?: string;
      status?: string;
      state?: string;
      conclusion?: string;
      detailsUrl?: string;
      targetUrl?: string;
    }>;
  };
  return {
    state: value.state,
    ...(value.mergedAt ? { mergedAt: value.mergedAt } : {}),
    ...(value.mergeCommit?.oid ? { mergeCommitSha: value.mergeCommit.oid } : {}),
    ...(value.headRefOid ? { headRefOid: value.headRefOid } : {}),
    ...(value.baseRefOid ? { baseRefOid: value.baseRefOid } : {}),
    ...(value.baseRefName ? { baseRefName: value.baseRefName } : {}),
    ...(value.mergeStateStatus ? { mergeStateStatus: value.mergeStateStatus } : {}),
    ...(value.mergeable ? { mergeable: value.mergeable } : {}),
    ...(value.reviewDecision ? { reviewDecision: value.reviewDecision } : {}),
    checks: (value.statusCheckRollup ?? []).flatMap((check) => {
      const name = check.name ?? check.context;
      if (!name) return [];
      return [{
        name,
        status: check.status ?? check.state ?? "UNKNOWN",
        ...(check.conclusion ? { conclusion: check.conclusion } : {}),
        ...(check.detailsUrl ?? check.targetUrl ? { detailsUrl: check.detailsUrl ?? check.targetUrl } : {}),
      }];
    }),
  };
}

export function defaultProjectTitle(repoRoot: string): string {
  return path.basename(repoRoot);
}
