import path from "node:path";
import { BrokerError } from "./errors.js";
import { runCommand } from "./process.js";
import type { BatchRecord, BrokerConfig, TaskRecord } from "./types.js";
import type { GitRepository } from "./git.js";

export interface PublicationResult {
  mode: "branch" | "pull-request";
  branchName: string;
  pullRequestUrl?: string;
  autoMergeEnabled?: boolean;
}

function renderTitle(template: string, batch: BatchRecord): string {
  return template.replaceAll("{batchId}", batch.id).replaceAll("{taskCount}", String(batch.taskIds.length));
}

function pullRequestBody(batch: BatchRecord, tasks: TaskRecord[]): string {
  const rows = tasks.map((task) => `- \`${task.id}\`${task.title ? ` — ${task.title}` : ""}`);
  return [
    "## Merge Broker batch",
    "",
    `Batch: \`${batch.id}\``,
    `Base: \`${batch.baseBranch}\` at \`${batch.baseSha}\``,
    "",
    "### Tasks",
    "",
    ...rows,
    "",
    "### Validation",
    "",
    ...batch.validations.map((result) => `- ${result.exitCode === 0 ? "✅" : "❌"} ${result.name}`),
    ...(batch.provenancePath
      ? ["", "### Provenance", "", `- Batch manifest: \`${batch.provenancePath}\``]
      : []),
    "",
    "Generated by Agent Merge Broker. Commit receipts and validation output remain in local broker state.",
  ].join("\n");
}

export async function publishBatch(options: {
  repo: GitRepository;
  config: BrokerConfig;
  batch: BatchRecord;
  tasks: TaskRecord[];
}): Promise<PublicationResult> {
  const { repo, config, batch, tasks } = options;
  if (!batch.branchName) throw new BrokerError("NO_BRANCH", `Batch ${batch.id} has no integration branch.`);
  if (config.publish.mode === "none") {
    throw new BrokerError("PUBLISH_DISABLED", "Publishing is disabled in .merge-broker/config.json.");
  }
  await repo.push(config.remote, batch.branchName);
  if (config.publish.mode === "branch") {
    return { mode: "branch", branchName: batch.branchName };
  }

  const title = renderTitle(config.publish.titleTemplate, batch);
  const args = [
    "pr",
    "create",
    "--base",
    config.baseBranch,
    "--head",
    batch.branchName,
    "--title",
    title,
    "--body-file",
    "-",
  ];
  if (config.publish.draft) args.push("--draft");
  for (const label of config.publish.labels) args.push("--label", label);
  const result = await runCommand("gh", args, {
    cwd: repo.root,
    input: pullRequestBody(batch, tasks),
  });
  const url = result.stdout
    .split("\n")
    .map((line) => line.trim())
    .find((line) => /^https?:\/\//u.test(line));
  if (!url) {
    throw new BrokerError("PUBLISH_FAILED", "GitHub CLI did not return a pull request URL.", {
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
  const autoMergeEnabled = config.publish.autoMerge ? await enableAutoMerge(repo.root, url, config) : false;
  return { mode: "pull-request", branchName: batch.branchName, pullRequestUrl: url, autoMergeEnabled };
}

export interface PullRequestMergeState {
  state: string;
  mergeStateStatus: string;
  mergeable: string;
}

/**
 * GitHub's own view of whether a pull request can merge. Returns undefined when the state cannot be
 * read at all, which is treated as "do not merge" rather than as permission to proceed.
 */
export async function readMergeState(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<PullRequestMergeState | undefined> {
  const result = await runCommand(
    "gh",
    ["pr", "view", pullRequestUrl, "--json", "state,mergeStateStatus,mergeable"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode !== 0) return undefined;
  try {
    const value = JSON.parse(result.stdout) as Partial<PullRequestMergeState>;
    return {
      state: value.state ?? "UNKNOWN",
      mergeStateStatus: value.mergeStateStatus ?? "UNKNOWN",
      mergeable: value.mergeable ?? "UNKNOWN",
    };
  } catch {
    return undefined;
  }
}

/**
 * Hands the merge decision to GitHub: it lands the pull request once required checks pass, and
 * updates the branch itself when the base branch requires it. The broker never pushes to the base
 * branch, so branch protection stays authoritative.
 */
export async function enableAutoMerge(
  repoRoot: string,
  pullRequestUrl: string,
  config: BrokerConfig,
): Promise<boolean> {
  const result = await runCommand(
    "gh",
    ["pr", "merge", pullRequestUrl, "--auto", `--${config.publish.mergeMethod}`],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode === 0) return true;

  // GitHub refuses to queue auto-merge on a pull request that is already mergeable, which happens
  // whenever the required checks finish before publication returns. Ask GitHub what the state is
  // instead of reading the CLI's prose, which differs across gh versions and locales.
  const mergeState = await readMergeState(repoRoot, pullRequestUrl);
  if (mergeState?.state === "MERGED") return true;
  if (mergeState?.mergeStateStatus === "CLEAN") {
    // "CLEAN" means mergeable with every required check already passed, so merging now is exactly
    // what the auto-merge queue would have done.
    const direct = await runCommand("gh", ["pr", "merge", pullRequestUrl, `--${config.publish.mergeMethod}`], {
      cwd: repoRoot,
      allowFailure: true,
    });
    if (direct.exitCode === 0) return true;
    throw new BrokerError("AUTO_MERGE_FAILED", "The pull request reported a clean merge state but did not merge.", {
      pullRequestUrl,
      mergeState,
      stdout: direct.stdout,
      stderr: direct.stderr,
    });
  }
  throw new BrokerError(
    "AUTO_MERGE_FAILED",
    "Could not enable auto-merge on the published pull request. Enable auto-merge in the repository settings, or set publish.autoMerge to false.",
    {
      pullRequestUrl,
      ...(mergeState ? { mergeState } : {}),
      stdout: result.stdout,
      stderr: result.stderr,
    },
  );
}

export async function inspectPullRequest(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<{ state: string; mergedAt?: string; mergeCommitSha?: string }> {
  const result = await runCommand(
    "gh",
    ["pr", "view", pullRequestUrl, "--json", "state,mergedAt,mergeCommit"],
    { cwd: repoRoot },
  );
  const value = JSON.parse(result.stdout) as {
    state: string;
    mergedAt?: string | null;
    mergeCommit?: { oid?: string } | null;
  };
  return {
    state: value.state,
    ...(value.mergedAt ? { mergedAt: value.mergedAt } : {}),
    ...(value.mergeCommit?.oid ? { mergeCommitSha: value.mergeCommit.oid } : {}),
  };
}

export function defaultProjectTitle(repoRoot: string): string {
  return path.basename(repoRoot);
}
