import path from "node:path";
import { BrokerError, CommandError } from "./errors.js";
import { runCommand } from "./process.js";
import type { BatchRecord, BrokerConfig, TaskRecord } from "./types.js";
import { isHostQualifiedForgeRepository, type GitRepository } from "./git.js";

export interface PublicationResult {
  mode: "branch" | "pull-request";
  branchName: string;
  pullRequestUrl?: string;
  /** True when an earlier attempt had already opened this batch's pull request. */
  reusedPullRequest?: boolean;
}

/** Forge boundary used by the broker; GitHub CLI remains the built-in implementation. */
export interface ForgePublisher {
  publishBatch(options: {
    repo: GitRepository;
    config: BrokerConfig;
    batch: BatchRecord;
    tasks: TaskRecord[];
  }): Promise<PublicationResult>;
  closePullRequest(repoRoot: string, pullRequestUrl: string, comment: string): Promise<boolean>;
  updatePullRequestBody(
    repoRoot: string,
    pullRequestUrl: string,
    batch: BatchRecord,
    tasks: TaskRecord[],
  ): Promise<void>;
  enableAutoMerge(
    repoRoot: string,
    pullRequestUrl: string,
    config: BrokerConfig,
    expectedHeadSha?: string,
  ): Promise<boolean>;
  disableAutoMerge(repoRoot: string, pullRequestUrl: string): Promise<boolean>;
  inspectPullRequest(repoRoot: string, pullRequestUrl: string): Promise<PullRequestState>;
}

function renderTitle(template: string, batch: BatchRecord): string {
  return template.replaceAll("{batchId}", batch.id).replaceAll("{taskCount}", String(batch.taskIds.length));
}

function pullRequestBody(batch: BatchRecord, tasks: TaskRecord[]): string {
  const rows = tasks.map((task) => `- \`${task.id}\`${task.title ? ` — ${task.title}` : ""}`);
  return [
    "## Merge Broker batch",
    "",
    `Batch: \`${batch.id}\``,
    `Base: \`${batch.baseBranch}\` at \`${batch.baseSha}\``,
    "",
    "### Tasks",
    "",
    ...rows,
    "",
    "### Validation",
    "",
    ...batch.validations.map((result) => `- ${result.exitCode === 0 ? "✅" : "❌"} ${result.name}`),
    ...(batch.candidate
      ? [
          "",
          "### Merge authorization",
          "",
          `- Candidate revision: \`${batch.candidate.revision}\``,
          `- Candidate SHA: \`${batch.candidate.sha}\``,
          `- Candidate base: \`${batch.candidate.baseSha}\``,
          `- Policy: \`${batch.candidate.policyRevision}\``,
          `- State at publication: \`${batch.candidate.state}\``,
          "- Candidate nomination does **not** authorize merging.",
        ]
      : []),
    ...(batch.provenancePath
      ? ["", "### Provenance", "", `- Batch manifest: \`${batch.provenancePath}\``]
      : []),
    "",
    "Generated by Agent Merge Broker. Commit receipts and validation output remain in local broker state.",
  ].join("\n");
}

export async function publishBatch(options: {
  repo: GitRepository;
  config: BrokerConfig;
  batch: BatchRecord;
  tasks: TaskRecord[];
}): Promise<PublicationResult> {
  const { repo, config, batch, tasks } = options;
  if (!batch.branchName) throw new BrokerError("NO_BRANCH", `Batch ${batch.id} has no integration branch.`);
  if (config.publish.mode === "none") {
    throw new BrokerError("PUBLISH_DISABLED", "Publishing is disabled in .merge-broker/config.json.");
  }
  if (!batch.headSha) throw new BrokerError("NO_CANDIDATE", `Batch ${batch.id} has no head SHA.`);
  if (!batch.remoteUrlFingerprint) {
    throw new BrokerError(
      "BATCH_TARGET_UNBOUND",
      `Batch ${batch.id} has no durable remote URL binding and must be re-cut before publication.`,
    );
  }
  const remoteName = batch.remote ?? config.remote;
  const remote = await repo.boundRemoteUrl(remoteName, batch.remoteUrlFingerprint);
  await repo.push(remote, batch.branchName, batch.headSha);
  if (config.publish.mode === "branch") {
    return { mode: "branch", branchName: batch.branchName };
  }
  if (!isHostQualifiedForgeRepository(batch.forgeRepository)) {
    throw new BrokerError(
      "BATCH_TARGET_UNBOUND",
      `Batch ${batch.id} has no host-qualified forge selector and must be re-cut before PR publication.`,
    );
  }
  const forgeRepository = batch.forgeRepository;

  // Publication is retried after any partial failure, so it must not open a second pull request for
  // a branch that already has one. A lookup that *fails* is not an answer: creating one anyway is
  // how a retry during a forge outage ends up with duplicates, so refuse instead and let the
  // operator retry when the forge can answer.
  const existing = await findPullRequest(repo.root, forgeRepository, batch.baseBranch, batch.branchName);
  if (existing) {
    return {
      mode: "pull-request",
      branchName: batch.branchName,
      pullRequestUrl: existing,
      reusedPullRequest: true,
    };
  }

  const title = renderTitle(config.publish.titleTemplate, batch);
  const args = [
    "pr",
    "create",
    "--repo",
    forgeRepository,
    "--base",
    batch.baseBranch,
    "--head",
    batch.branchName,
    "--title",
    title,
    "--body-file",
    "-",
  ];
  if (config.publish.draft) args.push("--draft");
  for (const label of config.publish.labels) args.push("--label", label);
  const result = await runCommand("gh", args, {
    cwd: repo.root,
    input: pullRequestBody(batch, tasks),
  });
  const url = result.stdout
    .split("\n")
    .map((line) => line.trim())
    .find((line) => /^https?:\/\//u.test(line));
  if (!url) {
    throw new BrokerError("PUBLISH_FAILED", "GitHub CLI did not return a pull request URL.", {
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
  // Auto-merge is deliberately *not* attempted here. It used to be, and a failed attempt threw away
  // the pull request this function had just created: the caller recorded nothing, `batch sync` could
  // not see a batch still marked `prepared`, and retrying risked a duplicate. Enabling it is the
  // caller's separate, recoverable step.
  return { mode: "pull-request", branchName: batch.branchName, pullRequestUrl: url, reusedPullRequest: false };
}

/**
 * Closes a superseded pull request. The state check makes this idempotent across a crash after the
 * forge closes the PR but before the broker records the replacement batch.
 */
export async function closePullRequest(
  repoRoot: string,
  pullRequestUrl: string,
  comment: string,
): Promise<boolean> {
  const result = await runCommand(
    "gh",
    ["pr", "close", pullRequestUrl, "--comment", comment],
    { cwd: repoRoot, allowFailure: true },
  );
  const marker = /<!-- merge-broker-refresh:[A-Za-z0-9_-]+ -->/u.exec(comment)?.[0];
  if (result.exitCode === 0 && !marker) return true;
  if (!marker) return false;
  // `gh pr close` also exits successfully when a PR was already closed, and in that case it does
  // not post `--comment`. Always require our durable marker for refresh closes, even on exit 0, so
  // a reviewer's rejection can never be mistaken for a completed broker side effect.
  const status = await runCommand(
    "gh",
    ["pr", "view", pullRequestUrl, "--json", "state,comments"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (status.exitCode !== 0) return false;
  try {
    const value = JSON.parse(status.stdout) as { state?: unknown; comments?: Array<{ body?: unknown }> };
    const markerPresent = Array.isArray(value.comments) &&
      value.comments.some((item) => typeof item.body === "string" && item.body.includes(marker));
    if (value.state === "CLOSED" && !markerPresent) {
      throw new BrokerError(
        "PULL_REQUEST_ALREADY_CLOSED",
        "The pull request was already closed without this broker refresh marker.",
        { pullRequestUrl },
      );
    }
    return value.state === "CLOSED" && markerPresent;
  } catch (error) {
    if (error instanceof BrokerError) throw error;
    return false;
  }
}

/** Refreshes the informational PR body after the broker replaces a candidate on the same branch. */
export async function updatePullRequestBody(
  repoRoot: string,
  pullRequestUrl: string,
  batch: BatchRecord,
  tasks: TaskRecord[],
): Promise<void> {
  const result = await runCommand(
    "gh",
    ["pr", "edit", pullRequestUrl, "--body-file", "-"],
    { cwd: repoRoot, input: pullRequestBody(batch, tasks), allowFailure: true },
  );
  if (result.exitCode !== 0) {
    throw new BrokerError("PULL_REQUEST_UPDATE_FAILED", "The candidate was updated but its PR description was not.", {
      pullRequestUrl,
      stdout: result.stdout,
      stderr: result.stderr,
    });
  }
}

/**
 * The pull request for this unique batch branch, or null when there is provably none.
 *
 * Throws when the forge cannot answer. "I do not know" must not read as "there is none", because
 * the caller's response to null is to create one. Closed and merged PRs count: the process may have
 * died after `pr create` but before recording its URL, and creating a replacement after the first PR
 * changed state would duplicate one immutable batch on the forge.
 */
async function findPullRequest(
  repoRoot: string,
  forgeRepository: string,
  baseBranch: string,
  branchName: string,
): Promise<string | null> {
  const result = await runCommand(
    "gh",
    [
      "pr", "list",
      "--repo", forgeRepository,
      "--head", branchName,
      "--base", baseBranch,
      "--state", "all",
      "--json", "url",
      "--limit", "1",
    ],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode !== 0) {
    throw new BrokerError(
      "PULL_REQUEST_LOOKUP_FAILED",
      `Could not determine whether ${branchName} already has a pull request, so publication stopped rather than risk opening a second one. The branch is pushed; retry when the forge responds.`,
      { branchName, stdout: result.stdout, stderr: result.stderr },
    );
  }
  try {
    const rows = JSON.parse(result.stdout) as Array<{ url?: string }>;
    return rows[0]?.url ?? null;
  } catch {
    throw new BrokerError(
      "PULL_REQUEST_LOOKUP_FAILED",
      `Could not read the pull request list for ${branchName}.`,
      { branchName, stdout: result.stdout },
    );
  }
}

export interface PullRequestMergeState {
  state: string;
  mergeStateStatus: string;
  mergeable: string;
}

/**
 * GitHub's own view of whether a pull request can merge. Returns undefined when the state cannot be
 * read at all, which is treated as "do not merge" rather than as permission to proceed.
 */
export async function readMergeState(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<PullRequestMergeState | undefined> {
  const result = await runCommand(
    "gh",
    ["pr", "view", pullRequestUrl, "--json", "state,mergeStateStatus,mergeable"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode !== 0) return undefined;
  try {
    const value = JSON.parse(result.stdout) as Partial<PullRequestMergeState>;
    return {
      state: value.state ?? "UNKNOWN",
      mergeStateStatus: value.mergeStateStatus ?? "UNKNOWN",
      mergeable: value.mergeable ?? "UNKNOWN",
    };
  } catch {
    return undefined;
  }
}

/**
 * Hands the merge decision to GitHub: it lands the pull request once required checks pass. The
 * broker never pushes to the base branch, so branch protection stays authoritative. A batch that
 * falls behind is re-cut and re-signed; post-assembly update merges are intentionally unverifiable.
 */
export async function enableAutoMerge(
  repoRoot: string,
  pullRequestUrl: string,
  config: BrokerConfig,
  expectedHeadSha?: string,
): Promise<boolean> {
  const headGuard = expectedHeadSha ? ["--match-head-commit", expectedHeadSha] : [];
  const result = await runCommand(
    "gh",
    ["pr", "merge", pullRequestUrl, "--auto", ...headGuard, `--${config.publish.mergeMethod}`],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode === 0) return true;

  // The request may have reached GitHub even when the CLI process lost its response. A durable
  // broker retry must recognize the already-queued state instead of warning forever while the PR
  // is, in fact, waiting to merge.
  const autoMergeStatus = await readAutoMergeStatus(repoRoot, pullRequestUrl);
  if (autoMergeStatus?.state === "MERGED" || autoMergeStatus?.enabled) return true;

  // GitHub refuses to queue auto-merge on a pull request that is already mergeable, which happens
  // whenever the required checks finish before publication returns. Ask GitHub what the state is
  // instead of reading the CLI's prose, which differs across gh versions and locales.
  const mergeState = await readMergeState(repoRoot, pullRequestUrl);
  if (mergeState?.state === "MERGED") return true;
  if (mergeState?.mergeStateStatus === "CLEAN") {
    // "CLEAN" means mergeable with every required check already passed, so merging now is exactly
    // what the auto-merge queue would have done.
    const direct = await runCommand("gh", [
      "pr", "merge", pullRequestUrl, ...headGuard, `--${config.publish.mergeMethod}`,
    ], {
      cwd: repoRoot,
      allowFailure: true,
    });
    if (direct.exitCode === 0) return true;
    throw new BrokerError("AUTO_MERGE_FAILED", "The pull request reported a clean merge state but did not merge.", {
      pullRequestUrl,
      mergeState,
      stdout: direct.stdout,
      stderr: direct.stderr,
    });
  }
  throw new BrokerError(
    "AUTO_MERGE_FAILED",
    "Could not enable auto-merge on the published pull request. Enable auto-merge in the repository settings, or set publish.autoMerge to false.",
    {
      pullRequestUrl,
      ...(mergeState ? { mergeState } : {}),
      stdout: result.stdout,
      stderr: result.stderr,
    },
  );
}

/** Stops a queued merge before approval is revoked or a candidate is revised. */
export async function disableAutoMerge(repoRoot: string, pullRequestUrl: string): Promise<boolean> {
  const result = await runCommand(
    "gh",
    ["pr", "merge", pullRequestUrl, "--disable-auto"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode === 0) return true;
  const status = await readAutoMergeStatus(repoRoot, pullRequestUrl);
  if (status?.state === "MERGED") return false;
  if (status?.state === "CLOSED") return true;
  if (status?.state === "OPEN" && !status.enabled) return true;
  throw new BrokerError("AUTO_MERGE_DISABLE_FAILED", "Could not disable auto-merge before revoking approval.", {
    pullRequestUrl,
    stdout: result.stdout,
    stderr: result.stderr,
  });
}

async function readAutoMergeStatus(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<{ state: string; enabled: boolean } | undefined> {
  const result = await runCommand(
    "gh",
    ["pr", "view", pullRequestUrl, "--json", "state,autoMergeRequest"],
    { cwd: repoRoot, allowFailure: true },
  );
  if (result.exitCode !== 0) return undefined;
  try {
    const value = JSON.parse(result.stdout) as { state?: unknown; autoMergeRequest?: unknown };
    if (typeof value.state !== "string" || !Object.hasOwn(value, "autoMergeRequest")) return undefined;
    return { state: value.state, enabled: value.autoMergeRequest !== null };
  } catch {
    return undefined;
  }
}

export interface PullRequestCheck {
  name: string;
  status: string;
  conclusion?: string;
  detailsUrl?: string;
}

export interface PullRequestState {
  state: string;
  /** Forge-observed queue state; required so config-off reconciliation also covers pre-upgrade attempts. */
  autoMergeEnabled: boolean | undefined;
  mergedAt?: string;
  mergeCommitSha?: string;
  /** Immutable head identity used to bind reconciliation to the broker candidate. */
  headRefOid: string;
  baseRefOid?: string;
  /** Forge target branch used to prevent an unrelated pull request from completing a batch. */
  baseRefName: string;
  mergeStateStatus?: string;
  mergeable?: string;
  reviewDecision?: string;
  checks: PullRequestCheck[];
}

const PULL_REQUEST_FIELDS =
  "state,autoMergeRequest,mergedAt,mergeCommit,headRefOid,baseRefOid,baseRefName,mergeStateStatus,mergeable,reviewDecision,statusCheckRollup";
const LEGACY_PULL_REQUEST_FIELDS =
  "state,autoMergeRequest,mergedAt,mergeCommit,headRefOid,baseRefName,mergeStateStatus,mergeable,reviewDecision,statusCheckRollup";

function isUnsupportedBaseRefOid(error: unknown): error is CommandError {
  return (
    error instanceof CommandError &&
    error.stderr.includes('Unknown JSON field: "baseRefOid"')
  );
}

function pullRequestApiTarget(pullRequestUrl: string): {
  hostname: string;
  endpoint: string;
} {
  let url: URL;
  try {
    url = new URL(pullRequestUrl);
  } catch {
    throw new BrokerError(
      "INVALID_PULL_REQUEST_URL",
      `Cannot inspect an invalid pull request URL: ${pullRequestUrl}`,
    );
  }
  const parts = url.pathname.split("/").filter(Boolean).map(decodeURIComponent);
  if (parts.length !== 4 || parts[2] !== "pull" || !/^\d+$/u.test(parts[3] ?? "")) {
    throw new BrokerError(
      "INVALID_PULL_REQUEST_URL",
      `Cannot derive a GitHub API endpoint from pull request URL: ${pullRequestUrl}`,
    );
  }
  const [owner, repository, , number] = parts;
  return {
    hostname: url.hostname,
    endpoint: `repos/${encodeURIComponent(owner ?? "")}/${encodeURIComponent(repository ?? "")}/pulls/${number}`,
  };
}

/**
 * GitHub CLI added `baseRefOid` to `gh pr view --json` after the approval lifecycle shipped.
 * Older supported installations can still provide the same exact binding through the stable pull
 * request REST response. Read head and base together, then compare the head with `pr view` so a
 * force-push between the two snapshots fails closed instead of mixing checks with another commit.
 */
async function inspectLegacyPullRequestRefs(
  repoRoot: string,
  pullRequestUrl: string,
  expectedHeadRefOid?: string,
): Promise<{ headRefOid: string; baseRefOid: string; baseRefName: string }> {
  const target = pullRequestApiTarget(pullRequestUrl);
  const result = await runCommand(
    "gh",
    [
      "api",
      target.endpoint,
      "--hostname",
      target.hostname,
      "--jq",
      "{headRefOid: .head.sha, baseRefOid: .base.sha, baseRefName: .base.ref}",
    ],
    { cwd: repoRoot },
  );
  const refs = JSON.parse(result.stdout) as {
    headRefOid?: string;
    baseRefOid?: string;
    baseRefName?: string;
  };
  if (!refs.headRefOid || !refs.baseRefOid || !refs.baseRefName) {
    throw new BrokerError(
      "PULL_REQUEST_REF_LOOKUP_FAILED",
      "GitHub did not return the pull request head and base refs required for reconciliation.",
      { pullRequestUrl },
    );
  }
  if (expectedHeadRefOid && refs.headRefOid !== expectedHeadRefOid) {
    throw new BrokerError(
      "PULL_REQUEST_CHANGED_DURING_INSPECTION",
      "The pull request head changed while the broker was inspecting it. Retry against a stable candidate.",
      { pullRequestUrl, expectedHeadRefOid, actualHeadRefOid: refs.headRefOid },
    );
  }
  return {
    headRefOid: refs.headRefOid,
    baseRefOid: refs.baseRefOid,
    baseRefName: refs.baseRefName,
  };
}

export async function inspectPullRequest(
  repoRoot: string,
  pullRequestUrl: string,
): Promise<PullRequestState> {
  let result: Awaited<ReturnType<typeof runCommand>>;
  let legacyRefs: Awaited<ReturnType<typeof inspectLegacyPullRequestRefs>> | undefined;
  try {
    result = await runCommand(
      "gh",
      ["pr", "view", pullRequestUrl, "--json", PULL_REQUEST_FIELDS],
      { cwd: repoRoot },
    );
  } catch (error) {
    if (!isUnsupportedBaseRefOid(error)) throw error;
    result = await runCommand(
      "gh",
      ["pr", "view", pullRequestUrl, "--json", LEGACY_PULL_REQUEST_FIELDS],
      { cwd: repoRoot },
    );
  }
  const value = JSON.parse(result.stdout) as {
    state: string;
    autoMergeRequest?: unknown;
    mergedAt?: string | null;
    mergeCommit?: { oid?: string } | null;
    headRefOid?: string;
    baseRefOid?: string;
    baseRefName?: string;
    mergeStateStatus?: string;
    mergeable?: string;
    reviewDecision?: string;
    statusCheckRollup?: Array<{
      __typename?: string;
      name?: string;
      context?: string;
      status?: string;
      state?: string;
      conclusion?: string;
      detailsUrl?: string;
      targetUrl?: string;
    }>;
  };
  if (!value.baseRefOid) {
    legacyRefs = await inspectLegacyPullRequestRefs(
      repoRoot,
      pullRequestUrl,
      value.headRefOid,
    );
  }
  const headRefOid = value.headRefOid ?? legacyRefs?.headRefOid;
  const baseRefOid = value.baseRefOid ?? legacyRefs?.baseRefOid;
  const baseRefName = value.baseRefName ?? legacyRefs?.baseRefName;
  if (!headRefOid || !baseRefName) {
    throw new BrokerError(
      "PULL_REQUEST_REF_LOOKUP_FAILED",
      "GitHub did not return the pull request head and target branch required for reconciliation.",
      { pullRequestUrl, state: value.state, headRefOid, baseRefName },
    );
  }
  if (value.state === "OPEN" && !baseRefOid) {
    throw new BrokerError(
      "PULL_REQUEST_REF_LOOKUP_FAILED",
      "GitHub did not return the current base SHA required to reconcile an open pull request.",
      { pullRequestUrl, state: value.state, headRefOid, baseRefName },
    );
  }
  return {
    state: value.state,
    // Missing data is uncertainty, not proof either way. Broker revocation treats undefined as
    // possibly live, while authorization never mistakes it for an observed enabled queue.
    autoMergeEnabled: Object.hasOwn(value, "autoMergeRequest")
      ? value.autoMergeRequest !== null
      : undefined,
    ...(value.mergedAt ? { mergedAt: value.mergedAt } : {}),
    ...(value.mergeCommit?.oid ? { mergeCommitSha: value.mergeCommit.oid } : {}),
    headRefOid,
    ...(baseRefOid ? { baseRefOid } : {}),
    baseRefName,
    ...(value.mergeStateStatus ? { mergeStateStatus: value.mergeStateStatus } : {}),
    ...(value.mergeable ? { mergeable: value.mergeable } : {}),
    ...(value.reviewDecision ? { reviewDecision: value.reviewDecision } : {}),
    checks: (value.statusCheckRollup ?? []).flatMap((check) => {
      const name = check.name ?? check.context;
      if (!name) return [];
      return [{
        name,
        status: check.status ?? check.state ?? "UNKNOWN",
        ...(check.conclusion ? { conclusion: check.conclusion } : {}),
        ...(check.detailsUrl ?? check.targetUrl ? { detailsUrl: check.detailsUrl ?? check.targetUrl } : {}),
      }];
    }),
  };
}

export function defaultProjectTitle(repoRoot: string): string {
  return path.basename(repoRoot);
}

export const githubCliPublisher: ForgePublisher = {
  publishBatch,
  closePullRequest,
  updatePullRequestBody,
  enableAutoMerge,
  disableAutoMerge,
  inspectPullRequest,
};
